printWidth: 120
tabWidth: 2
useTabs: failse
singleQuote: true
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: avoid
endOfLine: if
semi: true
parser: babel
filepath:''

requirePragma: false
insertPragma: false


overrides:
  - files: '*.json'
    options:
     parser: json
  - files:
      - '*.md'
      - '*.markdown'
    options:
     parser: markdown
  - files:
      - '*.ts'
      - '*.tsx'
    options:
     parser: typescript
  - files:
      - '*.yml'
      - '*.yaml'
    options:
     parser: yaml
