# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

executors:
  node-lts:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1 -dependencies-{{ checksum "package.json" }}
          - v1 -dependencies-

jobs:
  build:
    executor: node-lts
    steps:
      - setup
      - run: yarn
      - save_cache:
        paths:
          - node_modules
        key: v1 -dependencies-{{ checksum "package.json" }}

test:
  executor: node-lts
  steps:
      - setup
      - run:
        command: |
        yarn type-check
        yarn lint
        yarn coverage
      - store_artifacts:
        path: ~/repo/coverage

workflows:
  version 2
  test:
    jobs:
      - build
      - test:
        requires:
          - build

    # macos:
    #   xcode: 11.0.0 # Specify the Xcode version to use

    # steps:
    #   - checkout
    #   - run: pod install # Install CocoaPods dependencies
    #   - run: fastlane scan # Run tests using Fastlane

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      # - store_test_results:
      #     path: test_output
      # - store_artifacts:
      #     path: test_output
      #     destination: scan-output
